### PR TITLE
Create Unix-and-CommandLine.md

### PR DESCRIPTION
**Pull request by fadookie**
starter for resources on command line and unix

### CODE REVIEW

**Comment by Programazing** [comment]
Is this purely for *nix or all Operating Systems?

**Comment by Programazing** [comment]
Is this purely for *nix or for all Operating Systems?

**Comment by fadookie** [comment]
@Programazing This is for all *nix-family operating systems including Mac OS X.

**Comment by Programazing** [comment]
I think the name might not be as intuitive as it could be but for now it's fine.

**Pull request merged**
